[package]
name = "aetherion_shared"
edition = "2021"

[dependencies]
# Internal dependencies (Local Crates)
anyhow = { workspace = true } 
serde = { workspace = true } 
log = { workspace = true }
thiserror = { workspace = true }

# External dependency (Workspace-Inherited)
chrono = { workspace = true }